stages:
  - check
  - build
  - publish
  - deploy

variables:
  GIT_CLEAN_FLAGS: -f
  CACHE_IMAGE_TAG: 02724a80

default:
  # https://docs.gitlab.com/ee/ci/pipelines/settings.html#auto-cancel-pending-pipelines
  interruptible: true
  # Retry automatically incase the runner times out or there's a runner failure
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  tags:
    - veloren-docker

# NOTE: overriden for the `.tmacos` template so relevant changes need to be mirrored there
before_script:
  - source $HOME/.cargo/env
  - df -h /
  - free -h
  - cargo --version
  - export DISABLE_GIT_LFS_CHECK=true
  - export RUSTFLAGS="-D warnings"

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# For release builds that should only run when a commit on master is tagged
.tmastertag:
  rules:
    - if: $CI_COMMIT_TAG != null && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

include:
  - local: .gitlab/CI/check.gitlab-ci.yml
  - local: .gitlab/CI/build.gitlab-ci.yml
  - local: .gitlab/CI/publish.gitlab-ci.yml
