version: '3'

services:
 airshipper:
  image: airshipper:latest
  container_name: Airshipper
  restart: always
  volumes:
  - "/opt/airshipper/data/airshipper.db:/app/airshipper.db"
  env_file:
    - .airshipper-env
  ports:
    - "8080:8080"