# Example compose file
version: "3"

services:
  airshipper:
    container_name: Airshipper
    restart: always
    image: airshipper:latest
    volumes:
      - "/opt/airshipper/data/airshipper.db:/app/airshipper.db"
    # You can use `environment:` too
    env_file:
      - .airshipper-env
    ports:
      - "8080:8080"
