version: '3'

services:
 airshipper:
  image: airshipper:latest
  ports:
  - "8080:8080"
  volumes:
  # NOTE: run 'touch /opt/airshipper/data/server.ron' to create the config or docker
  # will create a folder called 'server.ron' which does not work.
  - "/opt/airshipper/data/server.ron:/app/server.ron" 
  - "/opt/airshipper/data/public:/app/public"
 db:
  image: postgres:11-alpine
  command: postgres -c 'max_connections=65'
  volumes:
  - "/opt/airshipper/data/postgres:/var/lib/postgresql/data"
  environment:
    POSTGRES_PASSWORD: airshipper