version: '3'

services:
 airshipper:
  image: airshipper:latest
  restart: on-failure
  volumes:
  # NOTE: run 'touch /opt/airshipper/data/airshipper/server.ron' to create the config or docker
  # will create a folder called 'server.ron' which does not work.
  - "/opt/airshipper/data/airshipper/server.ron:/app/server.ron" 
  - "/opt/airshipper/data/airshipper/public:/app/public"
 db:
  image: postgres:11-alpine
  restart: on-failure
  command: postgres -c 'max_connections=65'
  volumes:
  - "/opt/airshipper/data/postgres:/var/lib/postgresql/data"
  environment:
    POSTGRES_PASSWORD: example_password
 proxy:
  image: valian/docker-nginx-auto-ssl
  restart: on-failure
  ports:
  - "80:80"
  - "443:443"
  volumes:
  - /opt/airshipper/data/nginx:/etc/resty-auto-ssl
  environment:
    ALLOWED_DOMAINS: "example.com"
    SITES: "example.com=airshipper:8080"