[package]
name = "server"
version = "0.1.0"
authors = ["Songtronix <contact@songtronix.com>"]
edition = "2018"

# Sadly it is required to test with test feature enabled
# Otherwise the regular config will be used which results in a polluted environment
[features]
test = []

[dependencies]
# logging
fern = { version = "0.5.9", features = ["colored"] }
log = "0.4.8"
chrono = { version = "0.4.7", features = ["serde"] }
# Webserver
rocket = "0.4.2"
serde = "1.0.101"
serde_json = "1.0.41"
postgres = { version = "0.15.2", features = ["with-chrono"] }
# other
derive_more = "0.15.0"
reqwest = "0.9.19"
regex = "1.3.1"
lazy_static = "1.4.0"
ron = "0.5.1"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json", "serve", "postgres_pool"]
