[package]
name = "server"
version = "0.1.0"
authors = ["Songtronix <contact@songtronix.com>"]
edition = "2018"

[dependencies]
# logging
fern = { version = "0.5.9", features = ["colored"] }
log = "0.4.8"
chrono = { version = "0.4.7", features = ["serde"] }
# Webserver
rocket = "0.4.2"
serde = "1.0.101"
serde_json = "1.0.41"
# Database
rusqlite = { version = "0.14.0", features = ["chrono", "bundled"] } # TODO: Pretty outdated but rocket depends on it!
rust-s3 = "0.18.11"
# other
derive_more = "0.15.0"
reqwest = "0.9.19"
regex = "1.3.1"
lazy_static = "1.4.0"
dotenv = "0.15.0"
rocket_prometheus = "0.4.0"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json", "serve", "sqlite_pool"]
