apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "airshipper.configMapSettings" . }}
data:
  config.ron: |
    (
        channels: [
            (
                name: "nightly",
                gitlab_secret: "{{ .Values.gitlabSecret }}",
{{- if .Values.githubToken }}
                github_release_config: Some((
                    github_token: "{{ .Values.airshipper.githubToken }}",
                    github_repository_owner: "veloren",
                    github_repository: "veloren",
                    github_release: "{{ .Values.airshipper.githubRelease1 }}",
                )),
{{- else -}}
                github_release_config: None,
{{- end -}}
                channel_filters: [
                    ([
                        Stage("{{ .Values.artifactStage }}"),
                        TargetBranch("master"),
                        Variable("SCHEDULE_CADENCE","nightly"),
                    ]),
                ],
                build_map: [
                    (
                        filter: ([
                            BuildName("linux-x86_64"),
                        ]),
                        platform: (
                            os: "linux",
                            arch: "x86_64",
                        ),
                    ),
                    (
                        filter: ([
                            BuildName("linux-aarch64"),
                        ]),
                        platform: (
                            os: "linux",
                            arch: "aarch64",
                        ),
                    ),
                    (
                        filter: ([
                            BuildName("macos-x86_64"),
                        ]),
                        platform: (
                            os: "macos",
                            arch: "x86_64",
                        ),
                    ),
                    (
                        filter: ([
                            BuildName("macos-aarch64"),
                        ]),
                        platform: (
                            os: "macos",
                            arch: "aarch64",
                        ),
                    ),
                    (
                        filter: ([
                            BuildName("windows-x86_64"),
                        ]),
                        platform: (
                            os: "windows",
                            arch: "x86_64",
                        ),
                    ),
                ],
                webhooks: [],
            ),
            (
                name: "weekly",
                gitlab_secret: "{{ .Values.gitlabSecret }}",
{{- if .Values.githubToken }}
                github_release_config: Some((
                    github_token: "{{ .Values.githubToken }}",
                    github_repository_owner: "veloren",
                    github_repository: "veloren",
                    github_release: "{{ .Values.githubRelease2 }}",
                )),
{{- else -}}
                github_release_config: None,
{{- end -}}
                channel_filters: [
                    ([
                        Stage("{{ .Values.artifactStage }}"),
                        TargetBranch("master"),
                        Variable("SCHEDULE_CADENCE","weekly"),
                    ]),
                ],
                build_map: [
                    (
                        filter: ([
                            BuildName("linux-x86_64"),
                        ]),
                        platform: (
                            os: "linux",
                            arch: "x86_64",
                        ),
                    ),
                    (
                        filter: ([
                            BuildName("linux-aarch64"),
                        ]),
                        platform: (
                            os: "linux",
                            arch: "aarch64",
                        ),
                    ),
                    (
                        filter: ([
                            BuildName("macos-x86_64"),
                        ]),
                        platform: (
                            os: "macos",
                            arch: "x86_64",
                        ),
                    ),
                    (
                        filter: ([
                            BuildName("macos-aarch64"),
                        ]),
                        platform: (
                            os: "macos",
                            arch: "aarch64",
                        ),
                    ),
                    (
                        filter: ([
                            BuildName("windows-x86_64"),
                        ]),
                        platform: (
                            os: "windows",
                            arch: "x86_64",
                        ),
                    ),
                ],
                webhooks: [],
            ),
        ],
        data_path: "data",
{{- if .Values.gitlabToken }}
        gitlab_token: Some("{{ .Values.gitlabToken }}"),
{{- else -}}
        gitlab_token: None,
{{- end }}
    )