apiVersion: v1
kind: Service
metadata:
  name: {{ include "airshipper.service" . }}
  labels:
    {{- include "airshipper.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "airshipper.selectorLabels" . | nindent 4 }}
