# Access for the service account
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "airshipper.roleName" . }}
rules: []
---
# Binding the role to the account in default
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "airshipper.roleBindingName" . }}
subjects:
  - kind: ServiceAccount
    namespace: default
    name: {{ include "airshipper.serviceAccount" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "airshipper.roleName" . }}
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "airshipper.serviceAccount" . }}
  labels:
    {{- include "airshipper.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- with .Values.image.pullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}