# This workflow will create a release if a tag gets pushed.
# TODO: Should it compile releases incase of CI/CD gets changed (like artifacts.yml/check.yml) to verify that it works?

name: Create Release

on: 
  push:
    tags:
    - 'v*'

jobs:
  # Create a release draft
  build:
      runs-on: ubuntu-latest
      needs: [release-win, release-linux, release-macos]
      steps:
      - uses: actions/checkout@v1
      # Download windows artifact
      - uses: actions/download-artifact@v1
        with:
          name: airshipper-windows-installer
      # Download linux artifact
      - uses: actions/download-artifact@v1
        with:
          name: airshipper-linux
      # Download macos artifact
      - uses: actions/download-artifact@v1
        with:
          name: airshipper-macos
      # Create release draft with artifacts
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "airshipper-windows-installer, airshipper-linux, airshipper-macos"
          prerelease: true
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}