code-quality:
  stage: check
  except:
    - master
  image: registry.gitlab.com/veloren/veloren-docker-ci/cache/quality:${CACHE_IMAGE_TAG}
  tags: ["saas-linux-large-amd64"]
  script:
    - cargo clippy --all-targets --locked --all-features -- -D warnings
    - cargo fmt --all -- --check
    - cargo test --all-features

windows-msi:
  stage: check
  image: registry.gitlab.com/veloren/veloren-docker-ci/base/windows-x86_64:${CACHE_IMAGE_TAG}
  script:
    - cargo install cargo-bundle@0.6.1
    - cd client ## NOTE cargo bundle needs to be run from dir AND it needs to set the CARGO_TARGET_DIR, otherwise its some Path starting with /
    - CARGO_TARGET_DIR="./target" cargo bundle  --target=x86_64-pc-windows-gnu --release --all-features --format msi
    - ls -la .
    - mv ./target/x86_64-pc-windows-gnu/release/bundle/msi/airshipper.msi ../airshipper-windows.msi
  artifacts:
    paths:
      - airshipper-windows.msi
    expire_in: 1 week
